listenAddr = "127.0.0.1:5000"
verbose = true
#UserAgentID = "yourservernamehostname.example.org by yourcontactwebsite.org"

[gateway]
	# AllowedHosts = ["abc.localhost:8443", "abc.localhost:8080",	"myinternaldomain.local"] 
	[gateway.matrix]
		enabled = false
	[gateway.aesgcm]
	  enabled = false
[rewrite]
	[rewrite.webpushfcm]
		enabled = false
		# credentialsPath = "./vapid.key # path to the file containing VAPID private key

	# rewrite.fcm is deprecated. Please use webpushfcm instead.
	# [rewrite.fcm] # This is deprecated !
	#		enabled = false
	#		# credentialsPath = "" # credentials json path for any hostname
	#		[rewrite.fcm.CredentialsPaths] # keys for specific hostnames
				#"your.fcm.hostname.example.org" = "/path/to/your-service-account-file.json"
				#"other.fcm.hostname.example.org" = "/path/to/other-service-account-file.json"


# see https://codeberg.org/UnifiedPush/common-proxies/src/branch/main/docs/config.md for more info
