listenAddr = "127.0.0.1:5000"
verbose = true
#UserAgentID = "yourservernamehostname.example.org by yourcontactwebsite.org"

[gateway]
	# AllowedHosts = ["abc.localhost:8443", "abc.localhost:8080",	"myinternaldomain.local"] 
	[gateway.matrix]
		enabled = false
[rewrite]
	[rewrite.fcm]
		enabled = false
		# credentialsPath = "" # credentials json path for any hostname
		[rewrite.fcm.CredentialsPaths] # keys for specific hostnames
			#"your.fcm.hostname.example.org" = "/path/to/your-service-account-file.json"
			#"other.fcm.hostname.example.org" = "/path/to/other-service-account-file.json"


# see https://github.com/UnifiedPush/common-proxies/blob/main/docs/config.md for more info
