when:
  branch: main
  event: [push, pull_request, manual]

steps:
    check:
        # Same in Dockerfile
        image: golang:1.23
        commands:
          - make test

    upload:
        image: codeberg.org/s1m/woodpecker-upload:latest
        settings:
            token:
                from_secret: codeberg_token
            file:
                - up-rewrite
            package: true
